quarkus:
  http:
    port: 80
    #datasource:
    #db-kind: postgresql
    #username: posgres
    #password: gabu
    #  jdbc:
    #  url: jdbc:postgresql://localhost:5432/REMFONETIC
  container-image:
    group: ""
    name: ms-hipocoristico
    tag: latest
    registry: franciscoct
  kubernetes:
    namespace: app-datos
  profile: prod
  log:
    level: INFO
    file:
      enable: true
      path: ./log/log-ms-hipocoristico-hard.log
      level: INFO
      format: '{"log_data":{"fecha":"%d{yyyy-MM-dd HH:mm:ss}","Level":"%-5p","Mensaje":"%m","servicios":[%X{servicios}],"TiempoTotal":%X{tiempo}}}%n'
      rotation:
        max-file-size: 200M
        max-backup-index: 5
        rotate-on-boot: true
        file-suffix: .yyyy-MM-dd
  smallrye-openapi:
    path: /ms-hipocoristico-moli
    info-title: Contrato de Interfaz Microservicio Hipocoristico para modulo de concidencia de nombres.
    info-version: 1.0.0
    info-description: Contrato de Interfaz para la consulta de un nombres en base da datos para determinar si existe como hipocoristico y remplazarlo por su nombre real.

conexion:
  conexionesdb:
    c3remesas:
      credenciales:
        usuario: rL5KVE62kP3i1FJTaSmREA
        contrasena: MfeoIDy5dL4uEV2fH-YeMg
      ip: uYx3RV2-TQEHDr7-0gim9x4uZYdVw-suErVPWljmhWheenvOqDOHOy8UMbu135Y-cdzSPlp-Uy13DTM5wxlHmnV47cq_iJTHY331MDuW10A
      port: Y90BNCyOb8r61WBZigIEfA
      name: KiIPuiEfM53_RfP77oDDwg
      esquema: SC_FONET
      paquete: NA
      sp: FNDICCIONARIO